# 配置下载的文件保存的文件夹位置, 需要注意：需要写入绝对的文件路径
DOWNLOAD: 'C:\Users\Awey\Desktop\log'

# 保存了需要本地化路由列表的文件, 每一行即是一个地址
LINK_FILE: './m_links.py'

# 如你的默认输入法是中文, 需要指定 1 来切换输入法, 如果是英文, 则使用 0
SHIFT: 1

# 启动服务的 Debug 模式 (1 或 0)
DEBUG: 0

# 启动服务的绑定地址, 如使用 "127.0.0.1" 仅当前主机访问, "0.0.0.0" 当前局域网内可访问
HOST: '0.0.0.0'

# 启动服务的绑定端口号
PORT: 8009

# 下载目录的首个命名数字, 往后依次 +1
NUMBER: 220

# 操作滚动条的最大次数
SCROLL_MAX: 100

# 对已经生成了格式化本地文件的是否覆盖重新生成, 覆盖：1, 跳过：0
SHROUD: 0

# SLEEP_METHOD: 'auto' 方式下每执行一次下载后, 等待下载完成的休眠时间 (秒)
SLEEP_SECONDS: 60

# 执行一次下载后等待下载完成的方式
# manual: 手动执行, 按数字键 1 继续下一次下载
# auto: 自动执行, 自动休眠 SLEEP_SECONDS 秒后执行下一个下载任务
SLEEP_METHOD: 'auto'